# Generated by Django 5.1.3 on 2026-02-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('select_course', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('what_motivates_you_to_take_this_course', models.TextField()),
                ('experience_level', models.CharField(max_length=100)),
                ('education_level', models.CharField(max_length=100)),
                ('preferred_learning_schedule', models.CharField(max_length=100)),
                ('i_agree', models.BooleanField()),
                ('i_would_like_to_receive_updates', models.BooleanField()),
            ],
        ),
    ]
